version: "2.4"
services:
  front-end:
    depends_on:
      - back-end
    build: 
      args:
        - TEST_URL=http://back-end:9428
        - PROD_URL=http://back-end:8000
        - ENV=:e2e
      context: ./../front-end/
      dockerfile: Dockerfile
    image: frontend:9.9.9
    ports:
      - "8080:80"
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
  back-end:
    build: 
      args:
        - ENV=:e2e
      context: ./../backend/
      dockerfile: Dockerfile
    image: backend:9.9.9
    ports:
      - "9428:9428"
    healthcheck:
      test: curl --fail http://localhost:9428 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./../backend/database:/app/database:rw
  playwright:
    image: playwright:9.9.9
    depends_on:
      - front-end
    volumes:
      - ./../front-end/playwright-report:/app/playwright-report:rw
   # command: npx playwright test
    build:
      context: ./../front-end/
      dockerfile: Dockerfile-e2e
    environment:
      - FRONT_URL=http://front-end
