version: "2.4"
services:
  front-end:
    build: 
      args:
        - TEST_URL=http://localhost:9428
        - PROD_URL=http://localhost:8000
        - ENV=prod
      context: ./../front-end/
      dockerfile: Dockerfile
    image: frontend:6.6.6
    ports:
      - "8080:80"
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  back-end:
    build: 
      context: ./../backend/
      dockerfile: Dockerfile
    image: backend:6.6.6
    ports:
      - "8000:9428"
    volumes:
      - ./../backend/database:/app/database:rw
