version: "2.4"
services:
  front-end:
    depends_on:
      - back-end
    build: 
      args:
        - TEST_URL=http://back-end:9428
        - PROD_URL=http://back-end:8000
        - ENV=:production
      context: ./../front-end/
      dockerfile: Dockerfile
    image: frontend:6.6.6
    ports:
      - "8080:80"
    healthcheck:
      test: curl --fail http://front-end || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
  back-end:
    build: 
      args:
        - ENV=
      context: ./../backend/
      dockerfile: Dockerfile
    image: backend:6.6.6
    ports:
      - "8000:9428"
    healthcheck:
      test: curl -f http://back-end:9428/api/users || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./../backend/database:/app/database:rw
