version: "2.4"
services:
  front-end:
    depends_on:
      - back-end
    build: 
      args:
        - TEST_URL=http://localhost:8000
        - PROD_URL=http://localhost:8000
        - ENV=:e2e
      context: ./../front-end/
      dockerfile: Dockerfile
    image: frontend:9.9.9
    ports:
      - "8080:80"
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  back-end:
    build: 
      args:
        - ENV=:e2e
      context: ./../backend/
      dockerfile: Dockerfile
    image: backend:9.9.9
    ports:
      - "8000:9428"
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./../backend/database:/app/database:rw
  playwright:
    image: playwright:9.9.9
    depends_on:
      - front-end
    volumes:
      - ./../front-end/playwright-report:/playwright-report:rw
   # command: npx playwright test
    build:
      context: ./../front-end/
      dockerfile: Dockerfile-e2e
