version: "2.4"
services:
  front-end:
    build: 
      context: ./../front-end/
      dockerfile: Dockerfile
    image: frontend:6.6.6
    ports:
      - "8080:80"
  back-end:
    build: 
      context: ./../backend/
      dockerfile: Dockerfile
    image: backend:6.6.6
    ports:
      - "9428:9428"
